on: {push, pull_request}

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: make build
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: make test